create table ABITCARD_ABIT_CARD (
    ID uuid,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    --
    FIRSTNAME varchar(255),
    SECONDNAME varchar(255),
    DATE_ date,
    GENDER boolean,
    TRAINING_FORM varchar(50),
    NUMBER_PHONE integer,
    EMAIL varchar(50),
    DISCIPLIN1 varchar(255),
    BALL1 integer,
    DISCIPLIN2 varchar(255),
    BALL2 integer,
    DISCIPLIN3 varchar(255),
    BALL3 integer,
    DISCIPLIN4 varchar(255),
    BALL4 integer,
    DISCIPLIN5 varchar(255),
    BALL5 integer,
    DATE_SURRENDER varchar(255),
    INDIVIDUAL_ACHIEVEMENTS varchar(50),
    BALL6 integer,
    NATION integer,
    ID_DOCUMENTS varchar(50),
    SERIAS_NUMBER varchar(255),
    PLACE varchar(255),
    DATE_PASSPORT date,
    COUNTRY varchar(255),
    REGION_REGION varchar(255),
    CITY_CITY varchar(255),
    DISTRICT_DISTRICT varchar(255),
    STREET_STREET varchar(255),
    HOUSE varchar(255),
    FLAT varchar(255),
    FIRST_ID uuid,
    SECOND_ID uuid,
    THIRD_ID uuid,
    --
    primary key (ID)
);