alter table ABITCARD_CONNECTION add constraint FK_ABITCARD_CONNECTION_ON_FIRST foreign key (FIRST_ID) references ABITCARD_DIRECTION(ID);
alter table ABITCARD_CONNECTION add constraint FK_ABITCARD_CONNECTION_ON_SECOND foreign key (SECOND_ID) references ABITCARD_DIRECTION(ID);
alter table ABITCARD_CONNECTION add constraint FK_ABITCARD_CONNECTION_ON_THIRD foreign key (THIRD_ID) references ABITCARD_DIRECTION(ID);
create index IDX_ABITCARD_CONNECTION_ON_FIRST on ABITCARD_CONNECTION (FIRST_ID);
create index IDX_ABITCARD_CONNECTION_ON_SECOND on ABITCARD_CONNECTION (SECOND_ID);
create index IDX_ABITCARD_CONNECTION_ON_THIRD on ABITCARD_CONNECTION (THIRD_ID);
