alter table ABITCARD_HOME add constraint FK_ABITCARD_HOME_ON_REGION_REGION foreign key (REGION_REGION) references ABITCARD_REGION(ID);
create index IDX_ABITCARD_HOME_ON_REGION_REGION on ABITCARD_HOME (REGION_REGION);
