alter table ABITCARD_FIRST_LIST add constraint FK_ABITCARD_FIRST_LIST_ON_DIRECTION foreign key (DIRECTION_ID) references ABITCARD_FIRST_DIRECTION(ID);
alter table ABITCARD_FIRST_LIST add constraint FK_ABITCARD_FIRST_LIST_ON_LIST foreign key (LIST_ID) references ABITCARD_FIRST_LIST(ID);
create index IDX_ABITCARD_FIRST_LIST_ON_DIRECTION on ABITCARD_FIRST_LIST (DIRECTION_ID);
create index IDX_ABITCARD_FIRST_LIST_ON_LIST on ABITCARD_FIRST_LIST (LIST_ID);
